### ISSUE TITLE
Server crash if set.mm is not valid

### ISSUE THREAD

**Issue by glacode** [tirix/metamath-vspa#11]
Hi @tirix ,

to see if Diagnostics was implemented, I've changed the line

reelprrecn $p |- RR e. { RR , CC } $=

to

reelprrecn $p |- RR e. { RR , CCD } $=

and I get the error below:

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /*mydir*/.cargo/git/checkouts/metamath-knife-c0afdf58ccf11b37/0dbd297/src/grammar.rs:1295:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /*mydir*/.cargo/git/checkouts/metamath-knife-c0afdf58ccf11b37/0dbd297/src/database.rs:300:31
[Info  - 5:14:40 PM] Connection to server got closed. Server will restart.

**Comment by tirix** [comment]
Thanks!

This seems to be due to the fact that the `stmt_parse` statement parsing step of `metamath-knife` assumes that because previous steps have been run, its input is error-free, which is actually not the case.

I've submitted a fix in metamath-knife, but actually statement parsing step is currently unused, another option would have been to simply skip it.
